name: csx
channels:
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
  - defaults
  - nvidia
  - pytorch
  - pyg
  - conda-forge
  - https://mirrors.sjtug.sjtu.edu.cn/anaconda/cloud/pytorch/
  - https://mirrors.sjtug.sjtu.edu.cn/anaconda/cloud/conda-forge/
  - https://mirrors.sjtug.sjtu.edu.cn/anaconda/pkgs/msys2/
  - https://mirrors.sjtug.sjtu.edu.cn/anaconda/pkgs/r/
  - https://mirrors.sjtug.sjtu.edu.cn/anaconda/pkgs/main/
  - https://mirror.sjtu.edu.cn/anaconda/pkgs/main/
  - https://mirror.sjtu.edu.cn/anaconda/pkgs/free/
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - appdirs=1.4.4=pyhd3eb1b0_0
  - blas=1.0=mkl
  - bottleneck=1.3.5=py38h7deecbd_0
  - brotli=1.0.9=h5eee18b_7
  - brotli-bin=1.0.9=h5eee18b_7
  - brotlipy=0.7.0=py38h27cfd23_1003
  - bzip2=1.0.8=h7b6447c_0
  - ca-certificates=2023.01.10=h06a4308_0
  - certifi=2023.5.7=py38h06a4308_0
  - cffi=1.15.1=py38h5eee18b_3
  - charset-normalizer=2.0.4=pyhd3eb1b0_0
  - contourpy=1.0.5=py38hdb19cb5_0
  - cryptography=39.0.1=py38h9ce1e76_0
  - cuda-cudart=11.7.99=0
  - cuda-cupti=11.7.101=0
  - cuda-libraries=11.7.1=0
  - cuda-nvrtc=11.7.99=0
  - cuda-nvtx=11.7.91=0
  - cuda-runtime=11.7.1=0
  - cycler=0.11.0=pyhd3eb1b0_0
  - dbus=1.13.18=hb2f20db_0
  - expat=2.4.9=h6a678d5_0
  - ffmpeg=4.3=hf484d3e_0
  - fontconfig=2.14.1=h4c34cd2_2
  - fonttools=4.25.0=pyhd3eb1b0_0
  - freetype=2.12.1=h4a9f257_0
  - giflib=5.2.1=h5eee18b_3
  - glib=2.69.1=he621ea3_2
  - gmp=6.2.1=h295c915_3
  - gnutls=3.6.15=he1e5248_0
  - gst-plugins-base=1.14.1=h6a678d5_1
  - gstreamer=1.14.1=h5eee18b_1
  - icu=58.2=he6710b0_3
  - idna=3.4=py38h06a4308_0
  - importlib_resources=5.2.0=pyhd3eb1b0_1
  - intel-openmp=2023.1.0=hdb19cb5_46305
  - jinja2=3.1.2=py38h06a4308_0
  - joblib=1.1.1=py38h06a4308_0
  - jpeg=9e=h5eee18b_1
  - kiwisolver=1.4.4=py38h6a678d5_0
  - krb5=1.19.4=h568e23c_0
  - lame=3.100=h7b6447c_0
  - lcms2=2.12=h3be6417_0
  - ld_impl_linux-64=2.38=h1181459_1
  - lerc=3.0=h295c915_0
  - libbrotlicommon=1.0.9=h5eee18b_7
  - libbrotlidec=1.0.9=h5eee18b_7
  - libbrotlienc=1.0.9=h5eee18b_7
  - libclang13=14.0.6=default_he11475f_1
  - libcublas=11.10.3.66=0
  - libcufft=10.7.2.124=h4fbf590_0
  - libcufile=1.6.1.9=0
  - libcurand=10.3.2.106=0
  - libcusolver=11.4.0.1=0
  - libcusparse=11.7.4.91=0
  - libdeflate=1.17=h5eee18b_0
  - libedit=3.1.20221030=h5eee18b_0
  - libevent=2.1.12=h8f2d780_0
  - libffi=3.4.4=h6a678d5_0
  - libgcc-ng=11.2.0=h1234567_1
  - libgfortran-ng=11.2.0=h00389a5_1
  - libgfortran5=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libiconv=1.16=h7f8727e_2
  - libidn2=2.3.4=h5eee18b_0
  - libllvm14=14.0.6=hdb19cb5_3
  - libnpp=11.7.4.75=0
  - libnvjpeg=11.8.0.2=0
  - libpng=1.6.39=h5eee18b_0
  - libpq=12.9=h16c4e8d_3
  - libstdcxx-ng=11.2.0=h1234567_1
  - libtasn1=4.19.0=h5eee18b_0
  - libtiff=4.5.0=h6a678d5_2
  - libunistring=0.9.10=h27cfd23_0
  - libuuid=1.41.5=h5eee18b_0
  - libwebp=1.2.4=h11a3e52_1
  - libwebp-base=1.2.4=h5eee18b_1
  - libxcb=1.15=h7f8727e_0
  - libxkbcommon=1.0.1=h5eee18b_1
  - libxml2=2.10.3=hcbfbd50_0
  - libxslt=1.1.37=h2085143_0
  - lz4-c=1.9.4=h6a678d5_0
  - markupsafe=2.1.1=py38h7f8727e_0
  - matplotlib=3.7.1=py38h06a4308_1
  - matplotlib-base=3.7.1=py38h417a72b_1
  - mkl=2023.1.0=h6d00ec8_46342
  - mkl-service=2.4.0=py38h5eee18b_1
  - mkl_fft=1.3.6=py38h417a72b_1
  - mkl_random=1.2.2=py38h417a72b_1
  - munkres=1.1.4=py_0
  - ncurses=6.4=h6a678d5_0
  - nettle=3.7.3=hbbd107a_1
  - networkx=2.8.4=py38h06a4308_1
  - nspr=4.33=h295c915_0
  - nss=3.74=h0370c37_0
  - numexpr=2.8.4=py38hc78ab66_1
  - numpy=1.23.5=py38hf6e8229_1
  - numpy-base=1.23.5=py38h060ed82_1
  - openh264=2.1.1=h4ff587b_0
  - openssl=1.1.1t=h7f8727e_0
  - packaging=23.0=py38h06a4308_0
  - pandas=1.5.3=py38h417a72b_0
  - pcre=8.45=h295c915_0
  - pillow=9.4.0=py38h6a678d5_0
  - pip=23.0.1=py38h06a4308_0
  - ply=3.11=py38_0
  - pooch=1.4.0=pyhd3eb1b0_0
  - psutil=5.9.0=py38h5eee18b_0
  - pycparser=2.21=pyhd3eb1b0_0
  - pyg=2.3.0=py38_torch_1.13.0_cu117
  - pyopenssl=23.0.0=py38h06a4308_0
  - pyparsing=3.0.9=py38h06a4308_0
  - pyqt=5.15.7=py38h6a678d5_1
  - pyqt5-sip=12.11.0=py38h6a678d5_1
  - pysocks=1.7.1=py38h06a4308_0
  - python=3.8.16=h7a1cb2a_3
  - python-dateutil=2.8.2=pyhd3eb1b0_0
  - pytorch-cuda=11.7=h778d358_5
  - pytorch-mutex=1.0=cuda
  - pytz=2022.7=py38h06a4308_0
  - qt-main=5.15.2=h8373d8f_8
  - qt-webengine=5.15.9=hbbf29b9_6
  - qtwebkit=5.212=h3fafdc1_5
  - readline=8.2=h5eee18b_0
  - scikit-learn=1.2.2=py38h6a678d5_0
  - scipy=1.10.1=py38hf6e8229_1
  - setuptools=66.0.0=py38h06a4308_0
  - sip=6.6.2=py38h6a678d5_0
  - six=1.16.0=pyhd3eb1b0_1
  - sqlite=3.41.2=h5eee18b_0
  - tbb=2021.8.0=hdb19cb5_0
  - threadpoolctl=2.2.0=pyh0d69192_0
  - tk=8.6.12=h1ccaba5_0
  - toml=0.10.2=pyhd3eb1b0_0
  - torchaudio=0.13.1=py38_cu117
  - torchdiffeq=0.2.2=pyhd8ed1ab_0
  - torchvision=0.14.1=py38_cu117
  - tornado=6.2=py38h5eee18b_0
  - tqdm=4.65.0=py38hb070fc8_0
  - urllib3=1.26.15=py38h06a4308_0
  - wheel=0.38.4=py38h06a4308_0
  - xz=5.4.2=h5eee18b_0
  - zipp=3.11.0=py38h06a4308_0
  - zlib=1.2.13=h5eee18b_0
  - zstd=1.5.5=hc292b87_0
  - pip:
      - absl-py==2.1.0
      - alembic==1.13.1
      - annotated-types==0.7.0
      - anyio==4.4.0
      - argon2-cffi==23.1.0
      - argon2-cffi-bindings==21.2.0
      - arrow==1.3.0
      - asttokens==2.4.1
      - astunparse==1.6.3
      - async-lru==2.0.4
      - attrs==24.2.0
      - babel==2.16.0
      - backcall==0.2.0
      - beautifulsoup4==4.12.3
      - bleach==6.1.0
      - boto3==1.34.117
      - botocore==1.34.117
      - cachetools==5.3.3
      - click==8.1.7
      - cloudpickle==2.2.1
      - cmake==3.30.2
      - colorama==0.4.6
      - colorlog==6.8.2
      - comm==0.2.2
      - debugpy==1.8.5
      - decorator==5.1.1
      - defusedxml==0.7.1
      - dgl==2.1.0+cu117
      - dglke==0.1.0
      - dill==0.3.8
      - dnspython==2.3.0
      - docker-pycreds==0.4.0
      - exceptiongroup==1.1.1
      - executing==2.0.1
      - falcon==3.1.1
      - falcon-cors==1.1.7
      - fastdtw==0.3.4
      - fastjsonschema==2.20.0
      - filelock==3.12.0
      - flatbuffers==24.3.7
      - fqdn==1.5.1
      - fsspec==2024.5.0
      - future==1.0.0
      - gast==0.4.0
      - gitdb==4.0.10
      - gitpython==3.1.31
      - google-auth==2.29.0
      - google-auth-oauthlib==1.0.0
      - google-pasta==0.2.0
      - greenlet==3.0.3
      - grpcio==1.62.1
      - gunicorn==20.1.0
      - h11==0.14.0
      - h5py==3.10.0
      - httpcore==1.0.5
      - httplib2==0.22.0
      - httpx==0.27.2
      - huggingface-hub==0.23.2
      - igraph==0.11.4
      - importlib-metadata==7.1.0
      - iniconfig==2.0.0
      - ipykernel==6.29.5
      - ipython==8.12.3
      - ipywidgets==8.1.5
      - isodate==0.6.1
      - isoduration==20.11.0
      - jedi==0.19.1
      - jmespath==1.0.1
      - json5==0.9.25
      - jsonpointer==3.0.0
      - jsonschema==4.23.0
      - jsonschema-specifications==2023.12.1
      - jupyter==1.0.0
      - jupyter-client==8.6.2
      - jupyter-console==6.6.3
      - jupyter-core==5.7.2
      - jupyter-events==0.10.0
      - jupyter-lsp==2.2.5
      - jupyter-server==2.14.2
      - jupyter-server-terminals==0.5.3
      - jupyterlab==4.2.5
      - jupyterlab-pygments==0.3.0
      - jupyterlab-server==2.27.3
      - jupyterlab-widgets==3.0.13
      - kaleido==0.2.1
      - keras==2.13.1
      - libclang==18.1.1
      - lit==18.1.8
      - littleutils==0.2.2
      - lmdb==1.4.1
      - loguru==0.7.2
      - mako==1.3.2
      - markdown==3.6
      - matplotlib-inline==0.1.7
      - mistune==3.0.2
      - mpmath==1.3.0
      - nbclient==0.10.0
      - nbconvert==7.16.4
      - nbformat==5.10.4
      - nebula3-python==3.4.0
      - neo4j==5.16.0
      - nest-asyncio==1.6.0
      - notebook==7.2.2
      - notebook-shim==0.2.4
      - nvidia-cublas-cu11==11.10.3.66
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu11==11.7.101
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu11==11.7.99
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu11==11.7.99
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu11==8.5.0.96
      - nvidia-cudnn-cu12==8.9.2.26
      - nvidia-cufft-cu11==10.9.0.58
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu11==10.2.10.91
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu11==11.4.0.1
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu11==11.7.4.91
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-nccl-cu11==2.14.3
      - nvidia-nccl-cu12==2.18.1
      - nvidia-nvjitlink-cu12==12.6.20
      - nvidia-nvtx-cu11==11.7.91
      - nvidia-nvtx-cu12==12.1.105
      - oauthlib==3.2.2
      - ogb==1.3.6
      - openhgnn==0.6.0
      - opt-einsum==3.3.0
      - optuna==3.6.0
      - ordered-set==4.1.0
      - orion==0.2.7
      - outdated==0.2.2
      - overrides==7.7.0
      - pandocfilters==1.5.1
      - parso==0.8.4
      - pexpect==4.9.0
      - pickleshare==0.7.5
      - pkgutil-resolve-name==1.3.10
      - platformdirs==4.2.2
      - plotly==5.14.1
      - pluggy==1.0.0
      - prometheus-client==0.20.0
      - prompt-toolkit==3.0.47
      - protobuf==4.25.3
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - pyaml==23.5.9
      - pyasn1==0.5.1
      - pyasn1-modules==0.3.0
      - pydantic==2.8.2
      - pydantic-core==2.20.1
      - pygments==2.18.0
      - pymongo==4.3.3
      - pytest==7.3.1
      - python-igraph==0.11.4
      - python-json-logger==2.0.7
      - pyyaml==6.0
      - pyzmq==26.2.0
      - qtconsole==5.5.2
      - qtpy==2.4.1
      - rdflib==7.0.0
      - referencing==0.35.1
      - regex==2024.5.15
      - requests==2.32.3
      - requests-oauthlib==2.0.0
      - rfc3339-validator==0.1.4
      - rfc3986-validator==0.1.1
      - rpds-py==0.20.0
      - rsa==4.9
      - s3transfer==0.10.1
      - safetensors==0.4.3
      - scikit-optimize==0.9.0
      - seaborn==0.13.2
      - send2trash==1.8.3
      - sentry-sdk==1.45.0
      - setproctitle==1.3.3
      - smmap==5.0.0
      - sniffio==1.3.1
      - sortednp==0.5.0
      - soupsieve==2.6
      - sqlalchemy==2.0.29
      - stack-data==0.6.3
      - sympy==1.13.2
      - tabulate==0.9.0
      - tenacity==8.2.2
      - tensorboard==2.13.0
      - tensorboard-data-server==0.7.2
      - tensorflow==2.13.1
      - tensorflow-estimator==2.13.0
      - tensorflow-io-gcs-filesystem==0.34.0
      - termcolor==2.4.0
      - terminado==0.18.1
      - texttable==1.7.0
      - tinycss2==1.3.0
      - tokenizers==0.19.1
      - tomli==2.0.1
      - torch==2.0.0
      - torch-scatter==2.1.1+pt20cu117
      - torch-sparse==0.6.17+pt20cu117
      - torchdata==0.6.0
      - traitlets==5.14.3
      - transformers==4.41.2
      - triton==2.0.0
      - types-python-dateutil==2.9.0.20240821
      - typing-extensions==4.12.2
      - uri-template==1.3.0
      - wandb==0.16.6
      - wcwidth==0.2.13
      - webcolors==24.8.0
      - webencodings==0.5.1
      - websocket-client==1.8.0
      - werkzeug==3.0.1
      - widgetsnbextension==4.0.13
      - wrapt==1.16.0
prefix: /home/jpf/miniconda3/envs/csx
